AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  AskSDKs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AskSDKs
      Description: sdks for alexa
      ContentUri: 'files'
      CompatibleRuntimes:
        - nodejs8.10
      #LicenseInfo: 'YOUR LICENSE'
      #RetentionPolicy: Retain
Outputs:
  LayerVersionArn:
    Value: !Ref AskSDKs