service: practice-of-layer
description: To learn Lambda Layer by Alexa custom skill backend
frameworkVersion: ">=1.34.0"
provider:
  name: aws
  runtime: nodejs8.10

layers:
  hello:
    description: includes ask-sdk and ask-utils
    path: files
    compatibleRuntimes:
      - nodejs8.10

functions:
  hello:
    handler: index.handler
    layers:
      - {Ref: HelloLambdaLayer}